/* eslint-disable react/display-name */
/* eslint-disable no-param-reassign */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/plus.gltf --transform --t
*/

import { useGLTF } from '@react-three/drei';
import React, { forwardRef } from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { Box001: THREE.Mesh };
  materials: {};
};

const PlusModel = forwardRef<any, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes } = useGLTF('/plus.glb') as GLTFResult;

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.Box001.geometry} material={nodes.Box001.material} scale={0.025} />
    </group>
  );
});

export default PlusModel;

useGLTF.preload('/plus.glb');
