/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/chess.gltf --transform -S -i -t
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Chess001: THREE.Mesh;
  };
  materials: {
    ['Steel_-_Satin.001']: THREE.MeshStandardMaterial;
  };
};

function Chess(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/chess.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Chess001.geometry}
        material={materials['Steel_-_Satin.001']}
        position={[0.753, 6.191, -1.847]}
        rotation={[0, 0, 0.395]}
      />
    </group>
  );
}

useGLTF.preload('/models/chess.glb');

export default Chess;
