/* eslint-disable react/display-name */
/* eslint-disable no-param-reassign */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/plus.gltf --transform --t
*/

import { useGLTF } from '@react-three/drei';
import React, { forwardRef } from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { Box001: THREE.Mesh };
  materials: {};
};

const PlusModel = forwardRef<any, any>(({ material, ...props }, ref) => {
  const { nodes } = useGLTF('/models/plus.glb') as GLTFResult;

  return (
    <group ref={ref} {...props}>
      <mesh geometry={nodes.Box001.geometry} material={material ?? nodes.Box001.material} scale={0.025}></mesh>
    </group>
  );
});

export default PlusModel;

useGLTF.preload('/models/plus.glb');
