/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/sword.gltf --transform -S -i -t
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Mesh1_FrontColor_0: THREE.Mesh;
  };
  materials: {
    FrontColor: THREE.MeshStandardMaterial;
  };
};

export function Sword(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/sword.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh1_FrontColor_0.geometry}
        material={materials.FrontColor}
        position={[-12.981, 9.419, 19.499]}
        scale={0.005}
      />
    </group>
  );
}

useGLTF.preload('/models/sword.glb');

export default Sword;
