name: Code check

on:
  pull_request:
    branches: ['*']

jobs:
  Code-Check:
    runs-on: ubuntu-latest
    name: Code check
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Linter
        run: yarn lint

      - name: Format check
        run: yarn format:check

      - name: Type check
        run: yarn check-types